# Generated by Django 4.2.7 on 2023-12-03 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InitialPage', '0006_delete_activesdependecies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
                ('ubication', models.TextField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField()),
                ('typeofasset', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAssetsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyassets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyAssets.companyassets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAssetsUnityResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyassets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyAssets.companyassets')),
                ('responsableunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyAssets.responsableunity')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAssetsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyassets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyAssets.companyassets')),
                ('subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.subtypesactives')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.typesactives')),
            ],
        ),
        migrations.AddField(
            model_name='companyassets',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyAssets.origin'),
        ),
        migrations.CreateModel(
            name='ActivesDependecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencypercentage', models.FloatField()),
                ('descriptiondependency', models.TextField(max_length=100)),
                ('Interviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('companyassetsdependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyassetsdependent', to='CompanyAssets.companyassets')),
                ('companyassetsindependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyassetsindependent', to='CompanyAssets.companyassets')),
            ],
        ),
    ]
