# Generated by Django 4.2.4 on 2023-12-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyAssets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasifyActives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('damage', models.CharField(default='negligible', max_length=20)),
                ('critery', models.CharField(default='Irrelevant for practical purposes', max_length=50)),
                ('companyAssets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyAssets.companyassets')),
            ],
        ),
    ]
