# Generated by Django 4.2.4 on 2023-12-03 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIssueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('description', models.TextField(max_length=150)),
                ('statusScope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.statusissue')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=150)),
                ('issueSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.issuesource')),
                ('statusIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.statusissue')),
                ('typeIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.typeissuesource')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('statusGoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.statusissue')),
            ],
        ),
    ]
