# Generated by Django 4.2.7 on 2023-12-07 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('origin', models.CharField(max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('ubicationTipe', models.CharField(max_length=20)),
                ('ubication', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('characteristic', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantityValue', models.IntegerField()),
                ('cualityValue', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=15)),
                ('dimentionValue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubtypeAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.typeassets')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsDependence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentaje', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetIndepend', to='InitialPage.assets')),
                ('assetDepend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetDepend', to='InitialPage.assets')),
                ('responsableUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='responsableArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.departments'),
        ),
        migrations.AddField(
            model_name='assets',
            name='responsableUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='tipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialPage.typeassets'),
        ),
    ]
