# Generated by Django 4.2.7 on 2023-12-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0003_remove_actives_ubication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typesactives',
            name='subtypeActive',
        ),
        migrations.AddField(
            model_name='subtypesactives',
            name='typeActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.typesactives'),
        ),
    ]
