# Generated by Django 4.2.4 on 2023-12-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_workload_user_workload'),
        ('InitialPage', '0004_delete_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='workload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.workload'),
        ),
    ]
