# Generated by Django 5.0 on 2024-01-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0004_remove_assetsrisk_risk_assetsrisk_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safeguards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SafeguardsRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.risk')),
                ('safeguard', models.ManyToManyField(null=True, to='InitialPage.safeguards')),
            ],
        ),
    ]
