# Generated by Django 4.2.7 on 2023-12-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0005_departments_workload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='tipe',
            new_name='type',
        ),
    ]
