# Generated by Django 5.0 on 2024-01-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0005_safeguards_safeguardsrisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='safeguards',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.safeguardstypes'),
        ),
    ]
