# Generated by Django 4.2.7 on 2023-12-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0005_alter_actives_quantity_activesdependecies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivesDependecies',
        ),
    ]
