# Generated by Django 4.2.7 on 2023-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0006_rename_tipe_assets_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='ubicationTipe',
            new_name='ubicationType',
        ),
    ]
