# Generated by Django 5.0 on 2024-01-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0006_safeguardstypes_safeguards_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeguardsrisk',
            name='risk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.assetsrisk'),
        ),
    ]
