# Generated by Django 5.0 on 2024-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0007_alter_safeguardsrisk_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeguardsrisk',
            name='safeguard',
            field=models.ManyToManyField(to='InitialPage.safeguards'),
        ),
    ]
