# Generated by Django 4.2.7 on 2023-12-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0007_rename_ubicationtipe_assets_ubicationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsvalue',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InitialPage.assets'),
        ),
    ]
