# Generated by Django 4.2.7 on 2023-12-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0008_assetsvalue_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsvalue',
            name='subtype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
