# Generated by Django 5.0 on 2024-01-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InitialPage', '0010_remove_assetsvalue_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='origin',
        ),
    ]
