# Generated by Django 4.2.7 on 2023-12-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(max_length=13),
        ),
    ]
