# Generated by Django 4.2.4 on 2023-12-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_workload_user_workload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='celular',
            new_name='identity',
        ),
    ]
