# Generated by Django 4.2.4 on 2023-12-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_status_teamroles_user_teamrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workload',
        ),
        migrations.AlterField(
            model_name='teamroles',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
