# Generated by Django 4.2.7 on 2023-12-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_areas_responsabilities_teamwork_userresponsabilities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teamwork',
            new_name='Department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workArea',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.department'),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
