name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests and generate coverage report
        run: |
          export DJANGO_SETTINGS_MODULE=config.settings
          coverage run --source='.' -m pytest ActivosInformacion/InitialPage/tests.py
          coverage xml -o coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=JossueJativa_SeguridadDeLaInformacion
            -Dsonar.organization=jossuejativa
            -Dsonar.python.coverage.reportPaths=ActivosInformacion/coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
